-- Создание таблицы UserProject
create table Users
(
    id            int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          varchar(40)  NOT NULL,
    lastname      varchar(40)  NOT NULL,
    age           int check ( age > 0 ),
    email         varchar(40) UNIQUE,
    phone_number  varchar(20) UNIQUE,
    address       varchar(200) NOT NULL,
    date_of_birth DATE,
    created_at    TIMESTAMP,
    job           int
);

-- Добавление строк в таблицу UserProject
insert into users(name, lastname, age, email, phone_number, address)
values ('Semen', 'Bulytov', 36, 'bulytovs@mail.ru', '+7-999-99-99', 'Russia, Irkutsk, 999999');
insert into users(name, lastname, age, email, phone_number, address)
values ('Sevak', 'Martirosyan', 30, 'martirosyans@mail.ru', '+7-888-88-88', 'Armeniya, Baku, 888888');
insert into users(name, lastname, age, email, phone_number, address)
values ('Roman', 'Rogov', 37, 'rogovr@mail.ru', '+7-777-77-77', 'Russia, SPb, 777777');
insert into users(name, lastname, age, email, phone_number, address)
values ('Aidar', 'Orozbekov', 25, 'orozbekovai@mail.ru', '+7-666-66-66', 'Kurguzstan, Bishkek, 666666');

--------------------------------------------------------------------------------------------------------------

-- Создание таблицы Item
create table Item
(
    id        int primary key generated by default as identity,
    user_id   int          references users (id) on delete set null,
    item_name varchar(100) not null
);

-- Добавление строк в таблицу Item
insert into Item(user_id, item_name)
values (2, 'Airpods');
insert into Item(user_id, item_name)
values (1, 'Iphone 15');
insert into Item(user_id, item_name)
values (3, 'Macbook');
insert into Item(user_id, item_name)
values (4, 'Playstation');
insert into Item(user_id, item_name)
values (1, 'TV');

create table Role
(
    id   int primary key generated by default as identity,
    user_id   int          references users (id) on delete set null,
    name varchar(100) not null
);

insert into Role(user_id, name)
values (1, 'ADMIN');
insert into Role(user_id, name)
values (2, 'ADMIN');
insert into Role(user_id, name)
values (3, 'USER');
insert into Role(user_id, name)
values (4, 'USER');